server:
  port: 9091
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver: org.postgresql.Driver
   
  jpa:
    hibernate:
      ddl-auto: update
      
      